--- 
- hosts: all
  gather_facts: no
  tasks:
    - name: Start all instances referred to by inventory file
      local_action:
        module: ec2
        region: '{{item.value.region}}'
        state: 'running'
        instance_ids: [ "{{instance_id}}" ]
      when: instance_id is defined
      with_dict: '{{ec2_regions}}'

    - name: wait for them to come up
      local_action: wait_for port=22 host={{item}}
      with_items: '{{groups["all"]}}'
      run_once: yes
