
- hosts: all
  max_fail_percentage: 0
  roles:
    - { role: vicenteg.mapr_accounts }
    - { role: vicenteg.mapr_external_packages, tags: external, when: ansible_os_family == 'RedHat' }
    - { role: vicenteg.mapr_redhat_prereqs, when: ansible_os_family == 'RedHat' }
    - { role: vicenteg.mapr_debian_prereqs, when: ansible_os_family == 'Debian' }
    - { role: vicenteg.ntp }
    - { role: vicenteg.python_lxml }

- hosts: zookeepers
  max_fail_percentage: 0
  roles:
    - vicenteg.mapr_zookeeper

- hosts: cldb
  max_fail_percentage: 0
  roles:
    - vicenteg.mapr_cldb

- hosts: resourcemanager
  max_fail_percentage: 0
  roles:
    - { role: vicenteg.mapr_resourcemanager, when: yarn_enabled is defined and yarn_enabled == True }

- hosts: historyserver
  max_fail_percentage: 0
  roles:
    - { role: vicenteg.mapr_historyserver, when: yarn_enabled is defined and yarn_enabled == True }

- hosts: nodemanager
  max_fail_percentage: 0
  roles:
    - { role: vicenteg.mapr_nodemanager, when: yarn_enabled is defined and yarn_enabled == True }

- hosts: webserver
  roles:
    - vicenteg.mapr_webserver

- hosts: cluster
  roles:
    - vicenteg.mapr_nfs

- hosts: fileserver
  roles:
    - vicenteg.mapr_fileserver

- hosts: cluster
  roles:
    - { role: vicenteg.mapr_hbasemaster, when: hbase_enabled }
    - { role: vicenteg.mapr_hbaseregionserver, when: hbase_enabled }

- hosts: edge
  roles:
    - { role: vicenteg.mapr_client }

- hosts: all
  roles:
    - { role: vicenteg.mapr_configuration, tags: configuration }

- hosts: zookeepers
  roles:
    - { role: vicenteg.mapr_zookeeper_startup }

- hosts: cluster
  tasks:
    - name: tune MFS memory if memory is low
      sudo_user: root
      lineinfile: dest=/opt/mapr/conf/warden.conf regexp=service.command.mfs.heapsize.percent line=service.command.mfs.heapsize.percent=20 backup=yes
      when: ansible_memtotal_mb < 16384

    - name: tune MFS memory if memory is low
      sudo_user: root
      lineinfile: dest=/opt/mapr/conf/warden.conf regexp=service.command.mfs.heapsize.maxpercent line=service.command.mfs.heapsize.maxpercent=65 backup=yes
      when: ansible_memtotal_mb < 16384

- hosts: cldb
  roles:
    - { role: vicenteg.mapr_cldb_startup }

- hosts: cldb[0]
  sudo: yes
  sudo_user: mapr
  roles:
    - { role: vicenteg.mapr_maprlogin, when: secure_cluster is defined and secure_cluster == True }
  tasks:
    - name: set default desired replication to 1
      command: maprcli config save -values "{cldb.volumes.default.replication:1}"
      when: groups['cluster'] | length == 1

    - name: set default min replication to 1
      command: maprcli config save -values "{cldb.volumes.default.min.replication:1}"
      when: groups['cluster'] | length == 1

    - name: set replication to 1 if single node
      shell: maprcli volume list -columns volumename | grep -v volumename | awk '{print $1}' | xargs -n1 -I'{}' maprcli volume modify -name '{}' -replication 1 -minreplication 1
      when: groups['cluster'] | length == 1


- hosts: cluster
  roles:
    - { role: vicenteg.mapr_cluster_startup }

- hosts: cluster
  roles:
    - { role: vicenteg.mapr_license, when: license_file is defined and license_file != '' }

- hosts: mesos_master
  max_fail_percentage: 0
  roles:
    - vicenteg.mapr_mesos_master

- hosts: mesos_slave
  max_fail_percentage: 0
  roles:
    - vicenteg.mapr_mesos_slave
    - vicenteg.mapr_myriad

- hosts: hiveserver
  roles:
    - { role: vicenteg.mapr_hive, when: classic_enabled or yarn_enabled and hive_enabled is defined and hive_enabled == True }
    - { role: vicenteg.mapr_hive_test, tags: [ "test" ], when: classic_enabled or yarn_enabled and hive_enabled is defined and hive_enabled == True }

- hosts: cluster
  roles:
    - { role: vicenteg.mapr_pig, when: classic_enabled or yarn_enabled and pig_enabled is defined and pig_enabled == True }

- hosts: hue
  roles:
    - { role: vicenteg.mapr_httpfs, when: httpfs_enabled is defined and httpfs_enabled == True }

- hosts: cluster
  roles:
    - { role: vicenteg.mapr_solr, when: solr_enabled }

- hosts: oozie
  roles:
    - { role: vicenteg.mapr_oozie, when: classic_enabled or yarn_enabled and oozie_enabled is defined and oozie_enabled == True }

- hosts: hue
  roles:
    - { role: vicenteg.mapr-hue, when: hue_enabled is defined and hue_enabled == True }

- hosts: cluster
  roles:
    - { role: vicenteg.mapr_drill, tags: [ "drill" ], when: drill_enabled is defined and drill_enabled == True }
    - { role: vicenteg.mapr_drill_test, tags: [ "test" ], when: drill_enabled is defined and drill_enabled == True }

- hosts: spark_master
  sudo: yes
  roles:
    - { role: vicenteg.mapr_spark_master, when: spark_enabled is defined and spark_enabled and yarn_enabled is defined and yarn_enabled == False }

- hosts: spark_slave
  sudo: yes
  roles:
    - { role: vicenteg.mapr_spark_slave, when: spark_enabled is defined and spark_enabled }
    - { role: vicenteg.mapr_spark_test, tags: [ "test" ], when: spark_enabled is defined and spark_enabled and skip_tests == False }

- hosts: cluster
  sudo: yes
  roles:
    - { role: vicenteg.user_account, user: opentsdb, uid: 2147483631, group: opentsdb, gid: 2147483631, home: /home/opentsdb, when: opentsdb_enabled is defined and opentsdb_enabled == True }

- hosts: opentsdb
  sudo: yes
  roles:
    - { role: vicenteg.mapr_maprlogin, when: secure_cluster is defined and secure_cluster == True }
    - { role: vicenteg.mapr_opentsdb, when: opentsdb_enabled is defined and opentsdb_enabled == True }

- hosts: cluster
  roles:
    - { role: vicenteg.mapr_tcollector, when: opentsdb_enabled is defined and opentsdb_enabled == True }

- hosts: kafka
  roles:
    - { role: vicenteg.mapr-kafka, when: kafka_enabled is defined and kafka_enabled == True }

- hosts: edge
  roles:
    - { role: vicenteg.mapr_maprlogin, when: secure_cluster is defined and secure_cluster == True }
    - { role: vicenteg.mapr_loopbacknfs }

- hosts: edge;cluster
  sudo_user: mapr
  roles:
    - { role: vicenteg.mapr_post_install_test, tags: [ "test" ], when: skip_tests is defined and skip_tests == False }
