
- hosts: cluster
  roles:
    - mapr_redhat_prereqs

- hosts: zookeepers
  max_fail_percentage: 0
  roles:
    - mapr_zookeeper

- hosts: cldb
  max_fail_percentage: 0
  roles:
    - mapr_cldb

- hosts: resourcemanager
  max_fail_percentage: 0
  roles:
    - mapr_resourcemanager