--- 
- hosts: all
  gather_facts: no
  vars_files:
    - vars/global/main.yml
  tasks:
    - name: Start all instances referred to by inventory file
      local_action:
        module: ec2
        aws_access_key: '{{aws_access_key}}'
        aws_secret_key: '{{aws_secret_key}}'
        region: '{{item.value.region}}'
        state: 'stopped'
        instance_ids: [ "{{instance_id}}" ]
      when: instance_id is defined
      with_dict: ec2_regions
