
- hosts: all
  max_fail_percentage: 0
  roles:
    - mapr_redhat_prereqs
    - python_lxml

- hosts: zookeepers
  max_fail_percentage: 0
  roles:
    - mapr_zookeeper

- hosts: cldb
  max_fail_percentage: 0
  roles:
    - mapr_cldb

- hosts: resourcemanager
  max_fail_percentage: 0
  roles:
    - mapr_resourcemanager

- hosts: historyserver
  max_fail_percentage: 0
  roles:
    - mapr_historyserver

- hosts: nodemanager
  max_fail_percentage: 0
  roles:
    - mapr_nodemanager

- hosts: jobtracker
  max_fail_percentage: 0
  roles:
    - mapr_jobtracker

- hosts: tasktracker
  roles:
    - mapr_tasktracker

- hosts: webserver
  roles:
    - mapr_webserver

- hosts: cluster
  roles:
    - mapr_nfs

- hosts: fileserver
  roles:
    - mapr_fileserver

- hosts: edge
  roles:
    - mapr_client

- hosts: hiveserver
  roles:
    - mysql_server

- hosts: all
  roles:
    - mapr_configuration

- hosts: zookeepers
  roles:
    - mapr_zookeeper_startup

- hosts: cldb
  roles:
    - mapr_cldb_startup
